version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "netcracker-java"
      POSTGRES_USER: "kriuchkov"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
